name: gen_l10n_utils
description: A CLI tool for merging, flattening, and managing gen_l10n translation files.
version: 1.7.5
repository: https://github.com/AppMinds-dev/gen_l10n_utils
homepage: https://appminds.dev
documentation: https://github.com/AppMinds-dev/gen_l10n_utils/wiki
issue_tracker: https://github.com/AppMinds-dev/gen_l10n_utils/issues
environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  gen_l10n_utils: gen_l10n_utils

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  xml: ^6.5.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
  excel: ^4.0.6

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
  fake_async: ^1.3.2
  mockito: ^5.4.5
  build_runner: ^2.4.15

# Additional metadata for better discoverability
topics:
  - localization
  - arb
  - l10n
  - flutter

# Maintainer information
maintainers:
  - Manuel Bachl <manuel@appminds.dev>