name: appminds_l10n_tools
description: A CLI tool for merging, flattening, and managing gen_l10n translation files.
version: 1.0.0
repository: https://github.com/AppMinds-dev/appminds-l10n-tools
homepage: https://appminds.dev
documentation: https://github.com/AppMinds-dev/appminds-l10n-tools/wiki
issue_tracker: https://github.com/AppMinds-dev/appminds-l10n-tools/issues
publisher: appminds.dev
environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  al10n: al10n

dependencies:
  args: ^2.7.0
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.2.2

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
  fake_async: ^1.3.2
  mockito: ^5.4.5
  build_runner: ^2.4.15

# Additional metadata for better discoverability
topics:
  - localization
  - arb
  - l10n
  - flutter

# Maintainer information
maintainers:
  - Manuel Bachl <manuel@appminds.dev>
