name: Main Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_call:
    inputs:
      sdk:
        required: false
        type: string
        default: 'stable'

jobs:
  call_test_workflow:
    uses: ./.github/workflows/test.yml
    with:
      sdk: ${{ inputs.sdk }}