name: CI/CD

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'dev'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Generate mocks
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Create mock directory for tests
        run: mkdir -p /tmp/mock/temp

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed $(find . -name "*.dart" ! -name "*.mocks.dart")

      - name: Analyze project source
        run: dart analyze

      - name: Run tests with permission
        run: |
          echo "Running tests with full output..."
          dart test --chain-stack-traces --verbose-trace
        env:
          MOCK_BASE_PATH: /tmp/mock

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1